# Generated by Django 3.2.4 on 2021-06-12 22:14

import books.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0007_series'),
        ('books', '0002_alter_book_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='directories.publishinghouse', verbose_name='Издательство'),
        ),
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(default='Books/Book', upload_to=books.models.book_directory_path, verbose_name='Изображение'),
        ),
    ]
