# Generated by Django 3.2.4 on 2021-06-13 06:15

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210613_0114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authors',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(default='Books/book.png', upload_to=books.models.book_directory_path, verbose_name='Изображение'),
        ),
    ]
