# Generated by Django 3.2.4 on 2021-06-24 06:10

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(blank=True, default='Books/book0', upload_to=books.models.book_directory_path, verbose_name='Изображение'),
        ),
    ]
