# Generated by Django 3.2.4 on 2021-06-24 07:43

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20210624_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(blank=True, default='books/book0', upload_to=books.models.book_directory_path, verbose_name='Изображение'),
        ),
    ]
