# Generated by Django 3.2.4 on 2021-07-04 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_book_picture'),
        ('carts', '0004_alter_bookincart_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookincart',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books_in_cart', to='books.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='bookincart',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена за шт.'),
        ),
    ]
