# Generated by Django 3.2.4 on 2021-06-08 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='photo',
            new_name='picture',
        ),
    ]
