# Generated by Django 3.2.4 on 2021-06-09 07:40

import directories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0002_rename_photo_author_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='другой', max_length=30, verbose_name='Имя')),
                ('discription', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.AlterField(
            model_name='author',
            name='picture',
            field=models.ImageField(upload_to=directories.models.author_directory_path, verbose_name='Изображение'),
        ),
    ]
