# Generated by Django 3.2.4 on 2021-06-09 13:22

import directories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0003_auto_20210609_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='picture',
            field=models.ImageField(default='authors/Author', upload_to=directories.models.author_directory_path, verbose_name='Изображение'),
        ),
    ]
