# Generated by Django 3.2.4 on 2021-06-13 06:15

import directories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0007_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='picture',
            field=models.ImageField(default='authors/Author.png', upload_to=directories.models.author_directory_path, verbose_name='Изображение'),
        ),
    ]
