# Generated by Django 3.2.4 on 2021-07-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_phonenumber_order_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='information',
            field=models.TextField(blank=True, null=True, verbose_name='Доп. информация'),
        ),
    ]
