# Generated by Django 3.2.4 on 2021-07-06 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_auto_20210705_0926'),
        ('orders', '0004_alter_order_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='carts.cart', verbose_name='Заказ'),
        ),
    ]
